# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d446e469498f7ded96ef1d979689fccfde5864cb0eb0490ce802c4cf326409113f20cef72b7e3723b2d07587d2926f1a52c3783455d8186338408cace64e1d50

test:
  secret_key_base: 1c6b0eef4541e9e007bc5eaa10a26b599fddd9cd832f4189a5a1009fec648a014e36cc4da5aba297ffcac030fa63c037a3f850b88120fb0c9249b1ef5475b27d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
